// note: this helps modify / alter colors from a central point

enum colors {
    LIGHT_THEME_BACKGROUND_COLOR = "#F4F5F7",
    DARK_THEME_BACKGROUND_COLOR = "#000000",
    LIGHT_THEME_TEXT_COLOR = '#4D4D4D',
    DARK_THEME_TEXT_COLOR = '#4D4D4D',
    DROIDCONKE_BLUE = '#000CEB',
    DROIDCONKE_GREEN = '#00E2C3',
    DROIDCONKE_LIGHT_GREEN = '#7DE1C3',
    DROIDCONKE_BRICK_RED = '#FF6E4D',
    DROIDCONKE_BLACK = '#20201E',
    DROIDCONKE_DARK_GREY = '#707070',
    DROIDCONKE_LIGHT_GREY = '#00000075',
    DROIDCONKE_WHITE = '#FFFFFF',
    DROIDCONKE_PEARL = '#F5F5F5',
}